version: '3.3'

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus


spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN,USER